events {}

http {
    server {
        listen 443 ssl;
        listen 8443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/certs/server.crt;
        ssl_certificate_key /etc/nginx/certs/server.key;

        location /UserService {
            proxy_pass http://backend:8080/UserService;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
        }

        location /AccountService {
            proxy_pass http://backend:8081/AccountService;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}